1. Introduction
This assignment will help you to consolidate the concepts learnt in the session.
2. Problem Statement
Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
try:
  print("ZeroDivisionError catch with try and catch")
  num1=10
  num2=0
  result=num1/num2
except ZeroDivisionError as error:
  print("Exception details pleaase check your operation and maths rules" +str(error))


ZeroDivisionError catch with try and catch
Exception details division by zero
ERROR! Session/line number was not unique in database. History logging moved to new session 59


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [5]:
subject_values = ["Americans", "Indians"]
verb_values = ["Play", "watch"]
sports_values = ["Baseball","cricket"]
print("Implement a Python program to generate all sentences....")

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject_values for vb in verb_values for ob in sports_values]
for sentence in sentence_list:
 print ("'"+sentence +"'")

Implement a Python program to generate all sentences....
'Americans Play Baseball'
'Americans Play cricket'
'Americans watch Baseball'
'Americans watch cricket'
'Indians Play Baseball'
'Indians Play cricket'
'Indians watch Baseball'
'Indians watch cricket'


Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [8]:
# refer for code https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.vander.html
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

input_vector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(input_vector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(input_vector,no_col_opmat,True)

print("The input array is:",input_vector,"\n")


input_vector = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(input_vector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(input_vector,no_col_opmat,True)

print("---------------------------------------------------------------\n")
print("The input array is value is :",input_vector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")


------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

---------------------------------------------------------------

The input array is value is : [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 

